### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by antoniojgage** [steveo9219/coderefactor#1]
- You have a few code errors you need to clean up. Once you clean up this you will notice that when auto formatting your tags down fall in the same order as the original. 

- Also remember img tags are self-closing.

- You have an extra nav tag. Additionally the CLASS header was a hint to the semantic tag you should change it to.

![image](https://user-images.githubusercontent.com/7440005/79628142-10cdda80-8104-11ea-8696-deea064fc8a5.png)

**Comment by antoniojgage** [comment]
https://github.com/steveo9219/coderefactor/blob/a00dd2cac9ff24b72859e5e3f208becffe823793/index.html#L71

The rules in your CSS will make sense after CSS diner this will make sense.
The selector below says ANY element WITH TAG `nav` THAT has a PARENT with the class `header`
```
.header nav {
  padding-top: 15px;
  margin-right: 20px;
  float: right;
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  font-size: 20px;
}

**Comment by antoniojgage** [comment]
@steveo9219 check level 4 https://flukeout.github.io/

**Comment by antoniojgage** [comment]
@steveo9219 let me know if this makes sense.

**Comment by steveo9219** [comment]
@antoniojgage yes it did. I got passed that part 👌

**Comment by steveo9219** [comment]
Issues were cleaned up and homework was submitted
